export const FETCH_ONE_CHECKER_PROFILE = 'FETCH_ONE_CHECKER_PROFILE';
export const FETCH_ONE_CHECKER_PROFILE_SUCCESS =
  'FETCH_ONE_CHECKER_PROFILE_SUCCESS';
export const FETCH_ONE_CHECKER_PROFILE_FAILED =
  'FETCH_ONE_CHECKER_PROFILE_FAILED';

export const CREATE_ONE_CHECKER_PROFILE = 'CREATE_ONE_CHECKER_PROFILE';
export const CREATE_ONE_CHECKER_PROFILE_SUCCESS =
  'CREATE_ONE_CHECKER_PROFILE_SUCCESS';
export const CREATE_ONE_CHECKER_PROFILE_FAILED =
  'CREATE_ONE_CHECKER_PROFILE_FAILED';

export const UPDATE_ONE_CHECKER_PROFILE = 'UPDATE_ONE_CHECKER_PROFILE';
export const UPDATE_ONE_CHECKER_PROFILE_SUCCESS =
  'UPDATE_ONE_CHECKER_PROFILE_SUCCESS';
export const UPDATE_ONE_CHECKER_PROFILE_FAILED =
  'UPDATE_ONE_CHECKER_PROFILE_FAILED';
