export const CREATE_MANY_DEPT_FAMILY_SUBJECT =
  'CREATE_MANY_DEPT_FAMILY_SUBJECT';
export const CREATE_MANY_DEPT_FAMILY_SUBJECT_SUCCESS =
  'CREATE_MANY_DEPT_FAMILY_SUBJECT_SUCCESS';
export const CREATE_MANY_DEPT_FAMILY_SUBJECT_FAILED =
  'CREATE_MANY_DEPT_FAMILY_SUBJECT_FAILED';

export const FETCH_MY_DEPT_FAMILY_SUBJECT = 'FETCH_MY_DEPT_FAMILY_SUBJECT';
export const FETCH_MY_DEPT_FAMILY_SUBJECT_SUCCESS =
  'FETCH_MY_DEPT_FAMILY_SUBJECT_SUCCESS';
export const FETCH_MY_DEPT_FAMILY_SUBJECT_FAILED =
  'FETCH_MY_DEPT_FAMILY_SUBJECT_FAILED';
