export const CREATE_MANY_SUBJECT_DETAIL = 'CREATE_MANY_SUBJECT_DETAIL';
export const CREATE_MANY_SUBJECT_DETAIL_SUCCESS =
  'CREATE_MANY_SUBJECT_DETAIL_SUCCESS';
export const CREATE_MANY_SUBJECT_DETAIL_FAILED =
  'CREATE_MANY_SUBJECT_DETAIL_FAILED';

export const FETCH_MY_SUBJECT_DETAIL = 'FETCH_MY_SUBJECT_DETAIL';
export const FETCH_MY_SUBJECT_DETAIL_SUCCESS =
  'FETCH_MY_SUBJECT_DETAIL_SUCCESS';
export const FETCH_MY_SUBJECT_DETAIL_FAILED = 'FETCH_MY_SUBJECT_DETAIL_FAILED';
