export const CREATE_MANY_SUBJECT_LIKE = 'CREATE_MANY_SUBJECT_LIKE';
export const CREATE_MANY_SUBJECT_LIKE_SUCCESS =
  'CREATE_MANY_SUBJECT_LIKE_SUCCESS';
export const CREATE_MANY_SUBJECT_LIKE_FAILED =
  'CREATE_MANY_SUBJECT_LIKE_FAILED';

export const FETCH_MY_SUBJECT_LIKE = 'FETCH_MY_SUBJECT_LIKE';
export const FETCH_MY_SUBJECT_LIKE_SUCCESS = 'FETCH_MY_SUBJECT_LIKE_SUCCESS';
export const FETCH_MY_SUBJECT_LIKE_FAILED = 'FETCH_MY_SUBJECT_LIKE_FAILED';
