export const FETCH_SURVEY_COMPLETION = 'FETCH_SURVEY_COMPLETION';
export const FETCH_SURVEY_COMPLETION_SUCCESS =
  'FETCH_SURVEY_COMPLETION_SUCCESS';
export const FETCH_SURVEY_COMPLETION_FAILED = 'FETCH_SURVEY_COMPLETION_FAILED';
